# List of all case types:
case_types = [
    "ARB. A. (COMM.) - COMMERCIAL ARBITRATION UNDER SECTION 37 (2)",
    "ARBTN - ARBRITRATION CASES",
    "Bail Matters",
    "CA - CRIMINAL APPEAL",
    "CBI",
    "CC - CORRUPTION CASES",
    "CC NI ACT - Complaint Case 138 NI Act",
    "Contempt Petition",
    "Court Complaint",
    "C.R. Act 1954 - Comp. and Rehabilitation Act",
    "Cr. Case - CRIMINAL CASE",
    "CR Rev - CRIMINAL REVISION",
    "CS - CIVIL SUIT FOR CIVIL JUDGE",
    "CS (COMM.) - CIVIL SUIT (COMMERCIAL)",
    "CS DJ - CIVIL SUIT FOR DJ ADJ",
    "Ct. Cases - COMPLAINT CASES",
    "Dept.Eq - DEPARTMENTAL ENQUIRY",
    "Dpt. Eq - DEPARTMENTAL ENQUIRY",
    "E.P - Election Petition",
    "ESIC - Employee State Insurance Act",
    "EX. CIVIL - EXECUTION. CIVIL",
    "EX CRIMINAL - EXECUTION CRIMINAL",
    "Execution (Comm.) - Execution of Decree/order",
    "GP - GUARDIAN CASES",
    "HAM - HINDU ADOPTATION MAINT. ACT",
    "HMA - HINDU MARRIAGE ACT",
    "HTA - HOUSE TAX APPEAL",
    "IDA - INDIAN DIVORCE ACT",
    "Insolvency - Insolvency Case",
    "ITA - INDUSTRIAL TRIBUNAL",
    "LAC - LAND ACQ. ACT",
    "LC - LABOUR COURT",
    "LCA - Labour Court Application",
    "L.I.D. - Labour Industrial Dispute",
    "LIR - LABOUR/IND.TRIB REF. MATTER",
    "MACT - M.A.C.T.",
    "MC - MAHILA COURT",
    "MCA DJ - MISC. CIVIL APPEAL FOR DJ ADJ",
    "MCA SCJ - MISC. CIVIL APPEAL FOR CJ",
    "MCD APPL - MCD APPEAL",
    "MGP - Misc. Guardianship cases",
    "MHA - MENTAL HEALTH CASES",
    "MISC CRL - MISC. CASES CRIMINAL",
    "MISC DJ - MISC. CASES FOR DJ ADJ",
    "Misc Ex - Misc. Execution",
    "MISC SCJ - MISC. CASES FOR SCJ",
    "ML - MUSLIM LAW DELHI WAKF BOARD",
    "MPC - Misc.Probate cases",
    "Mt. CASE - MAINTENANCE PETITION",
    "OMP (COMM.) - COMMERCIAL ARBITRATION UNDER SECTION 34",
    "OMP (E) (COMM.) - COMMERCIAL ARBITRATION UNDER SECTION 27",
    "OMP (I) (COMM.) - COMMERCIAL ARBITRATION U/S 9",
    "OMP (MISC.) (COMM.) - COMMERCIAL ARBITRATION UNDER SECTION 29A",
    "OMP (T) (COMM.) - COMMERCIAL ARBITRATION UNDER SECTION 14 AND 15",
    "OP - Approval",
    "PC - PROBATE/LETTER OF ADMIN",
    "PPA - PUBLIC PREMISES ACT",
    "RCA DJ - REGULAR CIVIL APPEAL FOR DJ",
    "RC ARC - RENT CONTROLlER/ADDL. R.C.",
    "RCA SCJ - REGULAR CIVIL APPEAL FOR CJ",
    "RCT ARCT - RENT CTRL TRIBUNAL ADDL. R.C.T",
    "REC. CASES - RECEIVERSHIP CASES",
    "REVOCATION",
    "RP - Revision Petition",
    "RTI appeal - Right to Information Act appl",
    "SC - SESSIONS CASE",
    "S C Court - SMALL CAUSE COURT",
    "SMA - SPECIAL MARRIAGE ACT",
    "Succ. Court - SUCCESSION COURT",
    "TC - TRAFFIC CHALLAN",
    "T.P. Civ - Transfer Application",
    "T.P. Crl - Transfer Application(CRL)",
]
# Get rid of all '.' and '/' to make directories as they cause a conflict with unix naming scheme
# This has been stored in the folders list

# List of all data columns in output excel file:
cols = [
    "Id",
    "CombinedCaseNumber",
    "CaseNumber",
    "CaseType",
    "Year",
    "CourtName",
    "CourtHallNumber",
    "Bench",
    "DateFiled",
    "CaseClassification",
    "OrderType",
    "Petitioner",
    "PetitionerAdvocate",
    "Respondent",
    "RespondentAdvocate",
    "CurrentStage",
    "CurrentStatus",
    "District",
    "LastActionTaken",
    "LatestOrder",
    "BeforeHonarbleJudges",
    "LastPostedFor",
    "LastDateOfAction",
    "NextHearingDate",
    "LowerCourtName",
    "LowerCourtCaseNumber",
    "LowerCourtOtherDetails",
    "LowerCourtDisposalDate",
    "CaseGroup",
    "LastSyncTime",
    "RespondentType",
    "PetitionerType",
    "PresentedOn",
    "BenchCategory",
    "CaseOriginatedFrom",
    "ListedTimes",
    "Act",
    "DisposalDate",
    "LastListedOn",
    "CaseCategory",
    "CurrentPosition",
    "NextListingPurpose",
    "Purpose",
    "FilingNumber",
    "SerialNumber",
    "cnr_number",
    "CaseUpdateOn",
    "PoliceStationName",
    "NextListingCourt",
    "RegistrationDate",
    "ActionDate",
    "NextListingDate",
    "StageName",
    "PostingStage",
    "ListingDate",
    "NextListingTime",
    "DepartmentName",
    "LowerCourtJudgmentDate",
    "PresentDate",
    "StampNumber",
    "DateOfHearing",
    "LowerCourtDistrict",
    "LowerCourtJudges",
    "Subject",
    "CauseListDate",
    "RegistrationNo",
    "DecisionDate",
    "NatureOfDisposal",
    "PetitionerAddress",
    "RespondentAddress",
    "UnderActs",
    "UnderSections",
    "PoliceStation",
    "FIRNo",
    "BusinessOnDate",
    "hearing_business",
    "CourtState",
    "CourtType",
    "CourtDistrict",
    "StageOfCase",
    "CourtComplex",
    "FirstHearingDate",
    "ParsingYear",
    "Njdg_Judge_Name",
    "Full_Identifier",
    "CaseUniqueValue",
    "NoOfHearings",
    "NoOfOrders",
    "JudgementPDFlink",
    "JudgementContent",
]


# List of Courts => folder_name, court_name and links
COURTS = [
    # North-East Delhi (1), Shahdara(2), East-Delhi(3)
    {
        "folder_name": "KKD",
        "court_name": "Karkardooma Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=1",
    },
    # North Delhi(4), North-West Delhi(5)
    {
        "folder_name": "RHC",
        "court_name": "Rohini Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=4",
    },
    # South-West Delhi(6)
    {
        "folder_name": "DWK",
        "court_name": "Dwarka Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=6",
    },
    # New Delhi(7)
    {
        "folder_name": "PHC",
        "court_name": "Patiala House Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=7",
    },
    # Central Delhi(8)
    {
        "folder_name": "RAC",
        "court_name": "Rouse Avenue Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=8",
    },
    # West Delhi(9)
    # {
    #     'folder_name' : '',
    #     'court_name' : '',
    #     'url' : 'https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=9'
    # },
    # The site for West Delhi isn't working, it has no options to select a court complex.
    # Thus, it has been skipped for now.
    # South Delhi(10), South-East Delhi(11)
    {
        "folder_name": "SAK",
        "court_name": "Saket Court Complex",
        "url": "https://services.ecourts.gov.in/ecourtindia_v4_bilingual/cases/s_casetype.php?state=D&state_cd=26&dist_cd=10",
    },
]

# List of all case types with "." and "/" removed to suit the naming scheme of the folders
folders = [
    "ARB A (COMM) - COMMERCIAL ARBITRATION UNDER SECTION 37 (2)",
    "ARBTN - ARBRITRATION CASES",
    "Bail Matters",
    "CA - CRIMINAL APPEAL",
    "CBI",
    "CC - CORRUPTION CASES",
    "CC NI ACT - Complaint Case 138 NI Act",
    "Contempt Petition",
    "Court Complaint",
    "CR Act 1954 - Comp and Rehabilitation Act",
    "Cr Case - CRIMINAL CASE",
    "CR Rev - CRIMINAL REVISION",
    "CS (COMM) - CIVIL SUIT (COMMERCIAL)",
    "CS - CIVIL SUIT FOR CIVIL JUDGE",
    "Ct Cases - COMPLAINT CASES",
    "DeptEq - DEPARTMENTAL ENQUIRY",
    "Dpt Eq - DEPARTMENTAL ENQUIRY",
    "EP - Election Petition",
    "ESIC - Employee State Insurance Act",
    "EX CIVIL - EXECUTION CIVIL",
    "EX CRIMINAL - EXECUTION CRIMINAL",
    "Execution (Comm) - Execution of Decreeorder",
    "GP - GUARDIAN CASES",
    "HAM - HINDU ADOPTATION MAINT ACT",
    "HMA - HINDU MARRIAGE ACT",
    "HTA - HOUSE TAX APPEAL",
    "IDA - INDIAN DIVORCE ACT",
    "Insolvency - Insolvency Case",
    "LAC - LAND ACQ ACT",
    "LC - LABOUR COURT",
    "LCA - Labour Court Application",
    "LID - Labour Industrial Dispute",
    "LIR - LABOURINDTRIB REF MATTER",
    "MACT - MACT",
    "MC - MAHILA COURT",
    "MCA DJ - MISC CIVIL APPEAL FOR DJ ADJ",
    "MCA SCJ - MISC CIVIL APPEAL FOR CJ",
    "MCD APPL - MCD APPEAL",
    "MGP - Misc Guardianship cases",
    "MHA - MENTAL HEALTH CASES",
    "MISC CRL - MISC CASES CRIMINAL",
    "Misc Ex - Misc Execution",
    "MISC SCJ - MISC CASES FOR SCJ",
    "ML - MUSLIM LAW DELHI WAKF BOARD",
    "MPC - MiscProbate cases",
    "Mt CASE - MAINTENANCE PETITION",
    "OMP (COMM) - COMMERCIAL ARBITRATION UNDER SECTION 34",
    "OMP (E) (COMM) - COMMERCIAL ARBITRATION UNDER SECTION 27",
    "OMP (I) (COMM) - COMMERCIAL ARBITRATION US 9",
    "OMP (MISC) (COMM) - COMMERCIAL ARBITRATION UNDER SECTION 29A",
    "OMP (T) (COMM) - COMMERCIAL ARBITRATION UNDER SECTION 14 AND 15",
    "OP - Approval",
    "PC - PROBATELETTER OF ADMIN",
    "PPA - PUBLIC PREMISES ACT",
    "CS DJ - CIVIL SUIT FOR DJ ADJ",
    "ITA - INDUSTRIAL TRIBUNAL",
    "MISC DJ - MISC CASES FOR DJ ADJ",
    "RC ARC - RENT CONTROLlERADDL RC",
    "RCA DJ - REGULAR CIVIL APPEAL FOR DJ",
    "RCA SCJ - REGULAR CIVIL APPEAL FOR CJ",
    "RCT ARCT - RENT CTRL TRIBUNAL ADDL RCT",
    "REC CASES - RECEIVERSHIP CASES",
    "REVOCATION",
    "RP - Revision Petition",
    "RTI appeal - Right to Information Act appl",
    "S C Court - SMALL CAUSE COURT",
    "SC - SESSIONS CASE",
    "SMA - SPECIAL MARRIAGE ACT",
    "Succ Court - SUCCESSION COURT",
    "TC - TRAFFIC CHALLAN",
    "TP Civ - Transfer Application",
    "TP Crl - Transfer Application(CRL)",
]

print(len(case_types))
print(len(folders))

a = [i for i in case_types if i not in folders]

for ele in a:
    print(ele)